### ISSUE TITLE
> alert-join

### ISSUE THREAD

**Issue by tm21cy** [tm21cy/Bit#2]
Assigned to @net-tech.

Reference this issue for PRs.

**Comment by avasilic** [comment]
Alerts moderators when a user on the alert user list joins or leaves the server. Moderators can add, remove or list, alert users and can provide a reason for adding a user.

https://github.com/tm21cy/Bit/blob/c287c1960d3329386b6a6f5eaa683d1bb213f186/src/commands/moderation.ts#L76-L106
https://github.com/tm21cy/Bit/blob/c287c1960d3329386b6a6f5eaa683d1bb213f186/src/commands/moderation.ts#L349-L374
https://github.com/tm21cy/Bit/blob/c287c1960d3329386b6a6f5eaa683d1bb213f186/src/routes/JoinAlerts.ts#L10-L34
