### ISSUE TITLE
Suggestion: implement SQLite buffer file for query and rate optimizations

### ISSUE THREAD

**Issue by tm21cy** [tm21cy/Bit#26]
**Is your feature request related to a problem? Please describe.**
Planetscale limits our monthly queries, and any networking takes time. As well as this, we then rely on a network based backup.

**Describe the solution you'd like**
Approve and add a buffer file in SQLite for caching data - have two Sequelize entities, one configured for MySQL (raw queries and updates) and one for SQLite (take returned info and backup).

**Describe alternatives you've considered**
None suitable.

**Additional context**
None.

**Comment by avasilic** [comment]
This seems like a good idea.

**Comment by avasilic** [comment]
> Conflicts with Sequelize ORM implementation, plus very little inherent benefit upon testing.

@tm21cy
