### ISSUE TITLE
/helper-roles

### ISSUE THREAD

**Issue by tm21cy** [tm21cy/Bit#5]
Assigned to @net-tech, including all subcommands.

Reference this issue for PRs.

**Comment by avasilic** [comment]
Adds a user as a helper to a role(not a Discord Role).

https://github.com/tm21cy/Bit/blob/c287c1960d3329386b6a6f5eaa683d1bb213f186/src/commands/helper-roles.ts#L4-L29
https://github.com/tm21cy/Bit/blob/c287c1960d3329386b6a6f5eaa683d1bb213f186/src/routes/HelpRoles.ts#L1-L10
